#Prologue
define kristin     = Character("Kristin",      color="#1c0000", what_prefix='"', what_suffix='"', callback=name_callback, cb_name="kristin")
define boy_ald     = Character("Boy Aldorith", color="#1c0000", what_prefix='"', what_suffix='"', callback=name_callback, cb_name="boy_ald")
define girl_ald    = Character("Girl Aldorith",color="#1c0000", what_prefix='"', what_suffix='"', callback=name_callback, cb_name="girl_ald")
define yk          = Character("Yaoguai King", color="#1c0000", what_prefix='"', what_suffix='"', callback=name_callback, cb_name="yk") 
define narrator = Character(None, what_italic=False, callback=name_callback, cb_name=None)

# Chapter 1
define dorian                   = Character("Dorian",               color="#1c0000", callback=name_callback, cb_name="dorian")
define elara                    = Character("Elara",                color="#1c0000", callback=name_callback, cb_name="elara")
define lucas                    = Character("Lucas",                color="#1c0000", callback=name_callback, cb_name="lucas")
define sarah                    = Character("Sarah",                color="#1c0000", callback=name_callback, cb_name="sarah")
define emily                    = Character("Emily",                color="#1c0000", callback=name_callback, cb_name="emily")
define daniel                   = Character("Daniel",               color="#1c0000", callback=name_callback, cb_name="daniel")
define cyrus                    = Character("Paladin Cyrus",        color="#1c0000", callback=name_callback, cb_name="cyrus")
define feng                     = Character("Paladin Feng",         color="#1c0000", callback=name_callback, cb_name="feng")
define olympia                  = Character("Empress Olympia",      color="#1c0000", callback=name_callback, cb_name="olympia")
define long_shen                = Character("King Long Shen",       color="#1c0000", callback=name_callback, cb_name="long_shen")
define emperor_minjoon          = Character("Emperor Min-joon",     color="#1c0000", callback=name_callback, cb_name="emperor_minjoon")
define niko                     = Character("Niko",                 color="#1c0000", callback=name_callback, cb_name="niko")
define kaito                    = Character("Kaito",                color="#1c0000", callback=name_callback, cb_name="kaito")
define yuxuan                   = Character("Cheng Yuxuan",         color="#1c0000", callback=name_callback, cb_name=["supply_robot", "yuxuan"])
define vasily                   = Character("Count Vasily",         color="#1c0000", callback=name_callback, cb_name="vasily")
define gao                      = Character("Soldier Gao",          color="#1c0000", callback=name_callback, cb_name="gao")
define jiang                    = Character("Soldier Jiang",        color="#1c0000", callback=name_callback, cb_name="jiang")
define prosperity_dragon        = Character("Prosperity Dragon",    color="#1c0000", callback=name_callback, cb_name="prosperity_dragon")
define performers               = Character("Nervous Performer",    color="#1c0000", callback=name_callback, cb_name="performers")
define vendor                   = Character("Vendor",               color="#1c0000", callback=name_callback, cb_name="vendor")
define taotie                   = Character("Taotie",               color="#1c0000", callback=name_callback, cb_name="taotie")
define lead_fire_channeler      = Character("Lead Fire Channeler",  color="#1c0000", callback=name_callback, cb_name="lead_fire_channeler")
define female_guard             = Character("Female Guard",         color="#1c0000", callback=name_callback, cb_name="female_guard")
define male_soldier_1           = Character("Soldier",              color="#1c0000", callback=name_callback, cb_name="male_soldier_1")
define male_soldier_2           = Character("Soldier",              color="#1c0000", callback=name_callback, cb_name="male_soldier_2")
define woman_1                  = Character("Woman 1",              color="#1c0000", callback=name_callback, cb_name="woman_1")
define woman_3                  = Character("Woman 1",              color="#1c0000", callback=name_callback, cb_name="woman_3")
define man_1                    = Character("Man 1",                color="#1c0000", callback=name_callback, cb_name="man_1")
define man_2                    = Character("Man 2",                color="#1c0000", callback=name_callback, cb_name="man_2")
define man_3                    = Character("Man 3",                color="#1c0000", callback=name_callback, cb_name="man_3")
define yg                       = Character("Yaoguai",              color="#1c0000", callback=name_callback, cb_name="yg")

# Chapter 2
define svante                   = Character("Svante",               color="#1c0000", callback=name_callback, cb_name="svante")
define king_gustav              = Character("King Gustav",          color="#1c0000", callback=name_callback, cb_name="king_gustav")
define queen_ekaterina          = Character("Queen Ekaterina",      color="#1c0000", callback=name_callback, cb_name="queen_ekaterina")
define babala                   = Character("Babala",               color="#1c0000", callback=name_callback, cb_name="babala")
define herald                   = Character("Herald",               color="#1c0000", callback=name_callback, cb_name="herald")
define messenger                = Character("Messenger",            color="#1c0000", callback=name_callback, cb_name="messenger")
define mjoll_pavel              = Character("Soldier Pavel",        color="#1c0000", callback=name_callback, cb_name="mjoll_pavel")
define mjoll_helga              = Character("Soldier Helga",        color="#1c0000", callback=name_callback, cb_name="mjoll_helga")
define mjoll_lars               = Character("Soldier Lars",         color="#1c0000", callback=name_callback, cb_name="mjoll_lars")
define boy_ald_spa              = Character("Boy Aldorith",         color="#1c0000", callback=name_callback, cb_name="boy_ald_spa")
define girl_ald_spa             = Character("Girl Aldorith",        color="#1c0000", callback=name_callback, cb_name="girl_ald_spa")
define noblewoman               = Character("Noblewoman",           color="#1c0000", callback=name_callback, cb_name="noblewoman")
define vendor_mjoll             = Character("Vendor",               color="#1c0000", callback=name_callback, cb_name="vendor_mjoll")
define male_guard               = Character("Male Guard",           color="#1c0000", callback=name_callback, cb_name="male_guard")
define mjoll_male_soldier       = Character("Male Soldier",         color="#1c0000", callback=name_callback, cb_name="mjoll_male_soldier")
define mjoll_soldier_enby       = Character("Enby Soldier",         color="#1c0000", callback=name_callback, cb_name="mjoll_soldier_enby")
define mjoll_soldier_female_1   = Character("Female Guard",         color="#1c0000", callback=name_callback, cb_name="mjoll_soldier_female_1")
define mjoll_soldier_female_2   = Character("Female Guard",         color="#1c0000", callback=name_callback, cb_name="mjoll_soldier_female_2")
define mjoll_soldier_1          = Character("Mjoll Soldier",        color="#1c0000", callback=name_callback, cb_name="mjoll_soldier_1")
define mjoll_soldier_2          = Character("Mjoll Soldier",        color="#1c0000", callback=name_callback, cb_name="mjoll_soldier_2")


define frost_oni                = Character("",                     color="#1c0000", callback=name_callback, cb_name="frost_oni")
define qiongqi                  = Character("Qiongqi",              color="#1c0000", callback=name_callback, cb_name="qiongqi")
define supply_robot             = Character("Supply Bot",           color="#1c0000", callback=name_callback, cb_name="supply_robot")
define prophet_1                = Character("Prophet 1",            color="#1c0000", callback=name_callback, cb_name="prophet_1")
define prophet_2                = Character("Prophet 2",            color="#1c0000", callback=name_callback, cb_name="prophet_2")

# Chapter 3
define yuki_onna                = Character("Yuki-onna",            color="#1c0000", callback=name_callback, cb_name="yuki_onna")
define ekaterina_ghost          = Character("Queen Ekaterina",      color="#1c0000", callback=name_callback, cb_name="ekaterina_ghost")
define elias                    = Character("Elias",                color="#1c0000", callback=name_callback, cb_name="elias")
define niko_raven               = Character("Niko",                 color="#1c0000", callback=name_callback, cb_name="niko_raven")
define weng                     = Character("Miss Weng",            color="#1c0000", callback=name_callback, cb_name="weng")
define boy_ald_soldier          = Character("Boy Aldorith",         color="#1c0000", callback=name_callback, cb_name="boy_ald_soldier")
define girl_ald_soldier         = Character("Girl Aldorith",        color="#1c0000", callback=name_callback, cb_name="girl_ald_soldier")
define female_soldier_1         = Character("Female Soldier",       color="#1c0000", callback=name_callback, cb_name="male_soldier_2")

# Chapter 4
define chung_hee                = Character("Hyon Chung-hee",       color="#1c0000", callback=name_callback, cb_name="chung_hee")
define captain_sunwoo           = Character("Captain Sunwoo",       color="#1c0000", callback=name_callback, cb_name="captain_sunwoo")
define ji_hye                   = Character("Advisor Ji-hye",       color="#1c0000", callback=name_callback, cb_name="ji_hye")
define tian_xun                 = Character("Tian Xun",             color="#1c0000", callback=name_callback, cb_name="tian_xun")
define aoi                      = Character("Aoi",                  color="#1c0000", callback=name_callback, cb_name="aoi")
define tim                      = Character("Tim",                  color="#1c0000", callback=name_callback, cb_name="tim")
define tedda                    = Character("Tedda",                color="#1c0000", callback=name_callback, cb_name="tedda")
define carriage_driver          = Character("Carriage Driver",      color="#1c0000", callback=name_callback, cb_name="carriage_driver")
define prophet                  = Character("Prophet",              color="#1c0000", callback=name_callback, cb_name="prophet")
define courtier_1               = Character("Courtier 1",           color="#1c0000", callback=name_callback, cb_name="courtier_1")
define courtier_2               = Character("Courtier 2",           color="#1c0000", callback=name_callback, cb_name="courtier_2")
define servant                  = Character("Servant",              color="#1c0000", callback=name_callback, cb_name="servant")
define dae_hyun                 = Character("Park Dae-hyun",        color="#1c0000", callback=name_callback, cb_name="dae_hyun")

# Chapter 5
define roboto                   = Character("Roboto",               color="#1c0000", callback=name_callback, cb_name="roboto")
define magnus                   = Character("Magnus",               color="#1c0000", callback=name_callback, cb_name="magnus")
define seo_yeon                 = Character("Empress Seo-yeon",     color="#1c0000", callback=name_callback, cb_name="seo_yeon")
define door_voice               = Character("Door",                 color="#1c0000", callback=name_callback, cb_name="door_voice")

# Chapter 6
define hundun                   = Character("Hundun",               color="#1c0000", callback=name_callback, cb_name="hundun")
define olympia_illusion         = Character("Empress Olympia",      color="#1c0000", callback=name_callback, cb_name="olympia_illusion")
define gustav_illusion          = Character("King Gustav",          color="#1c0000", callback=name_callback, cb_name="gustav_illusion")
define minjoon_illusion         = Character("Emperor Min-joon",     color="#1c0000", callback=name_callback, cb_name="minjoon_illusion")

# Chapter 7
define woman_2                  = Character("Woman 2",              color="#1c0000", callback=name_callback, cb_name="woman_2")
define male_soldier_ch7         = Character("Male Soldier",         color="#1c0000", callback=name_callback, cb_name="male_soldier_ch7")

# Chapter 8
define hwan_sik                 = Character("Baek Hwan-sik",        color="#1c0000", callback=name_callback, cb_name="hwan_sik")
define spirit                   = Character("Spirit",               color="#1c0000", callback=name_callback, cb_name="spirit")
define olympia                  = Character("Empress Olympia",      color="#1c0000", callback=name_callback, cb_name="olympia")

# Chapter 9
define huli_jing                = Character("Huli Jing",            color="#1c0000", callback=name_callback, cb_name="huli_jing")
define fynn                     = Character("Fynn",                 color="#1c0000", callback=name_callback, cb_name="fynn")
define katashi                  = Character("Katashi",              color="#1c0000", callback=name_callback, cb_name="katashi")
define emi                      = Character("Emi",                  color="#1c0000", callback=name_callback, cb_name="emi")
define seorin                   = Character("Seorin",               color="#1c0000", callback=name_callback, cb_name="seorin")
define feng                     = Character("Paladin Feng",         color="#1c0000", callback=name_callback, cb_name="feng")
define soldier_gao              = Character("Soldier Gao",          color="#1c0000", callback=name_callback, cb_name="soldier_gao")

# Chapter 10
# none