###############################################################################
#  01_voice_autoplay.rpy
#  Auto-voicing hook. No per-line "voice ..." statements needed anywhere
#  in your scripts, and no dependency on Ren'Py's built-in translation-id
#  auto-voice feature.
#
#  Requires: voice_line_ids.json and voice_map.json in the game/ folder,
#  generated by build_voice_map.py (run that script after adding or
#  editing dialogue / recording new voice files).
#
#  This file must load before any dialogue plays, hence the "01_" prefix
#  (Ren'Py loads .rpy files in alphabetical order) and init -1 priority.
###############################################################################

init -1 python:

    import json
    import os

    def _voice_load_json(name):
        path = os.path.join(renpy.config.gamedir, name)
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        return {}

    # "a1b2c3d4e5f6" -> "audio/voice/a1b2c3d4e5f6.ogg"
    # Only contains lines that currently have a recorded audio file.
    _VOICE_MAP = _voice_load_json("voice_map.json")

    # "game/script.rpy:123" -> "a1b2c3d4e5f6"
    # Regenerated fresh every time build_voice_map.py runs, so this
    # always matches current line numbers in your scripts.
    _VOICE_LINE_IDS = _voice_load_json("voice_line_ids.json")

    def auto_voice_callback(event, interact=True, **kwargs):
        """
        Assigned to config.character_callback, which Ren'Py calls for
        EVERY Character that speaks (including the narrator), in
        addition to any per-character callback already in use
        (e.g. sprite-highlight callbacks are unaffected by this).
        """
        if event != "begin":
            return

        # Gives the exact source location of the say statement that
        # is currently executing.
        filename, line = renpy.get_filename_line()
        key = "%s:%d" % (filename, line)

        line_id = _VOICE_LINE_IDS.get(key)
        if line_id is None:
            return

        voice_path = _VOICE_MAP.get(line_id)
        if voice_path:
            renpy.voice(voice_path)

    config.character_callback = auto_voice_callback

    def reload_voice_map():
        """
        Optional dev helper -- call from the console or a debug
        screen to reload the JSON files without restarting the game,
        e.g. after re-running build_voice_map.py mid-session.
        """
        global _VOICE_MAP, _VOICE_LINE_IDS
        _VOICE_MAP = _voice_load_json("voice_map.json")
        _VOICE_LINE_IDS = _voice_load_json("voice_line_ids.json")
        renpy.notify("Voice map reloaded (%d lines, %d with audio)" %
                    (len(_VOICE_LINE_IDS), len(_VOICE_MAP)))
